---
title: "VSS 2025 Submission"
author: [Rick O. Gilmore, Julia DiFulvio, Brianna Beamer, Nicole Cruz]
affiliation: The Pennsylvania State University
format: 
  html: default
  pdf: default
---

## Poster title

Synthesizing evidence about developmental patterns in human visual acuity as measured by Teller Acuity Cards

## Authors

Rick Gilmore (rog1@psu.edu), Julia DiFulvio, Brianna Beamer, Nicole Cruz; The Pennsylvania State University

## Abstract

Replication is a cornerstone of scientific rigor and a prerequisite for cumulative science. This project synthesized evidence from published research that employed a widely used measure of grating visual acuity (VA), Teller Acuity Cards (TAC). We sought to capture findings about the development of VA in early childhood into an aggregated dataset and share the dataset openly. Online literature searches identified papers that mentioned “teller acuity cards”, “visual acuity cards”, or “teller cards”. We found n=745 papers published from 1974-2024. Next, we identified empirical papers that used TAC to measure VA and which reported VA in an extractable tabular form. To-date, n=250 of 316 papers with available PDF versions have been evaluated and n=14 have been identified that present extractable data meeting our screening criteria. Available datasets represent more than n=3,991 participants and 7 countries (Australia, Brazil, Canada, China, Italy, Mexico, and the U.S.). As expected, group VA increases from birth to 36-months, with faster rates of change among children tested binocularly (0.47 cyc/deg per month) than those tested monocularly (0.35 cyc/deg per month). Group VA values at similar ages vary substantially across studies, especially in children older than 12 months. Our synthesis of published TAC VA data confirms anticipated age-related trends and points to avenues for future research, particularly regarding what factors account for cross-study and by-country differences in rates of development. We hope our soon-to-be openly shared dataset contributes toward a more cumulative science of visual development.

## Status

The poster was accepted on February 6, 2025. It will be presented as follows:

*Poster Session*: Development: Infants, children \
*Date/Time*: Sunday, May 18, 2025, 2:45 – 6:45 pm \
*Location*: Pavilion \
